[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_job_board = "7cp6bK3S7VoM5rmhE1Qcqk2KZCQxTmD4GU8QoauZYVTp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/denimcodes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
